package com.lucaswangdev.mapper;

import com.lucaswangdev.common.BaseMapper;
import com.lucaswangdev.model.UserDO;
import com.lucaswangdev.params.UserParam;
import com.lucaswangdev.params.ext.UserParamExt;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * UserMapperBase.
 * auto generated by MyBatis Generator Plugin, please do not modify it!
 */
@Repository
public interface UserMapper extends BaseMapper<UserParam, UserDO> {

    /**
     * 根据条件查询记录
     * @param param
     * @return
     */
    List<UserDO> queryListByParamExt(UserParamExt param);

    /**
     * 根据条件查询记录数
     * @param param
     * @return
     */
    Long queryCountByParamExt(UserParamExt param);

    /* DO_NOT_MODIFY_ABOVE */

    Long queryCountByParamExt3(UserParamExt param);

}