package com.lucaswangdev.model;

import com.lucaswangdev.common.BaseDO;
import org.apache.ibatis.type.Alias;

import java.io.Serializable;

/**
* 用户表
* <p>
* UserDO.
* </p>
* <p>
* auto generated by MyBatis Generator Plugin, please do not modify it!
* </p>
*/
@Alias("UserDO")
public class UserDO extends BaseDO implements Serializable {

	private static final long serialVersionUID = 1764515928931881018L;
    /**
    * 主键
    * type BIGINT
    */
    private Long id;
    /**
    * 创建时间
    * type DATETIME
    */
    private java.util.Date gmtCreate;
    /**
    * 更新时间
    * type DATETIME
    */
    private java.util.Date gmtModified;
    /**
    * 用户名
    * type VARCHAR
    */
    private String userName;
    /**
    * 性别
    * type VARCHAR
    */
    private String sex;
    /**
    * 地址
    * type VARCHAR
    */
    private String address;
  
    /**
    * getter 主键
    */
	@Override
	public Long getId() {
		return id;
	}

    /**
    * setter 主键
    */
	@Override
	public void setId(Long id) {
		this.id = id;
	}

    /**
    * getter 创建时间
    */
	@Override
	public java.util.Date getGmtCreate() {
		return gmtCreate;
	}

    /**
    * setter 创建时间
    */
	@Override
	public void setGmtCreate(java.util.Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
    * getter 更新时间
    */
	@Override
	public java.util.Date getGmtModified() {
		return gmtModified;
	}

    /**
    * setter 更新时间
    */
	@Override
	public void setGmtModified(java.util.Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
    * getter 用户名
    */
	public String getUserName() {
		return userName;
	}

    /**
    * setter 用户名
    */
	public void setUserName(String userName) {
		this.userName = userName;
	}

    /**
    * getter 性别
    */
	public String getSex() {
		return sex;
	}

    /**
    * setter 性别
    */
	public void setSex(String sex) {
		this.sex = sex;
	}

    /**
    * getter 地址
    */
	public String getAddress() {
		return address;
	}

    /**
    * setter 地址
    */
	public void setAddress(String address) {
		this.address = address;
	}

  
}